name: Cppcheck
'on':
  workflow_dispatch: null
  schedule:
  - cron: 0 1 * * *
  push: null
jobs:
  docker_check:
    name: Cppcheck
    uses: steinwurf/cppcheck-action/.github/workflows/action.yml@2.0.0
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
