name: Raspberry Pi
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
jobs:
  RaspberryPi:
    uses: steinwurf/cross-compile-action/.github/workflows/action.yml@6.0.0
    with:
      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}
      name: Raspberry Pi
      cxx_mkspec: cxx_raspberry_gxx83_armv7
      image: ghcr.io/steinwurf/gcc-8.3.0-raspberrypi-armv7:1.0.0
      test_runner: raspberry_pi
      test_binary_name: rely_tests
      test_binary_directory: build/cxx_raspberry_gxx83_armv7/test
      test_files: test/encode_decode_decoder.json test/encode_decode_encoder.json
        test/symbol_encode_decode_symbol_encoder.json test/symbol_encode_decode_symbol_decoder.json
        test/symbol_encode_decode_encode_queue.json
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
